### ISSUE TITLE
Бонус-задание #2.2 - Семантическое версионирование

### ISSUE THREAD

**Issue by xokvictor** [ilya-volkov-ip51/cv#3]
В данном проекте установим такие понятия:
Develop ветка - для непрерывной разработки.
Master ветка - для выпуска версий продукта.

Так как первый этап вашей разработки успешно завершен, можно выпускать версию:
- произведите pull request из develop в master и завершите слияние.
- установите тег на коммите в ветке master, получившемся в результате слияния. Тег назовите согласно правилам семантического версионирования.

В результате вы получите свою первую версию продукта.

**Comment by ilya-volkov-ip51** [comment]
Completed!

**Comment by xokvictor** [comment]
Замечания:
- Первую версию обычно называют 0.1.0
- Тег с версией отсутствует

**Comment by ilya-volkov-ip51** [comment]
исправил

**Comment by ilya-volkov-ip51** [comment]
А еще задания будут? Интересные очень. Хотелось бы еще что-то новое сделать.

**Comment by xokvictor** [comment]
Не исправлено. Вы назвали коммит по-другому. А нужно было проставить тег. Тег проставляется как описано тут: http://bit.ly/1NsGAA4

Когда у Вас все получится, то тег должен отобразиться в списке:

<img width="1124" alt="2016-05-13 09 52 40" src="https://cloud.githubusercontent.com/assets/10273585/15240195/93dc86a4-18f0-11e6-9bd4-d1a5c195e1ae.png">

**Comment by xokvictor** [comment]
Внесите исправления ;)

On 22 April 2016 at 17:00, ilya-volkov-ip51 <notifications@github.com>
wrote:

> А еще задания будут? Интересные очень. Хотелось бы еще что-то новое
> сделать.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/ilya-volkov-ip51/cv/issues/3#issuecomment-213440189>
>



-- 

*С уважением,Виктор*

**Comment by ilya-volkov-ip51** [comment]
Вроде получилось, просто до этого не использовал консольный гит, а загружал файлы вручную. Теперь разобрался

**Comment by xokvictor** [comment]
Done!
